apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msa-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/soulee-dev/argo-test.git
    targetRevision: HEAD
    path: apps
    directory:
      recurse: false
      exclude: 'app-of-apps.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
